# Generated by Django 4.0.1 on 2022-01-19 14:19

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.SmallIntegerField(default=0, validators=[blog.models.validate_rating]),
        ),
    ]
